BesselBasis_trainable: true
PolynomialCutoff_p: 6
allow_tf32: false
append: true
ase_args:
  format: extxyz
avg_num_neighbors: auto
batch_size: 1
chemical_symbol_to_type:
  H: 0
  O: 1
conv0_layers: 1
dataset: ase
dataset_file_name: /datasets/water/water-dataset.extxyz
dataset_seed: 456
default_dtype: float32
early_stopping_cumulative_delta: false
early_stopping_delta:
  validation_loss: 0.005
early_stopping_lower_bounds:
  LR: 1.0e-06
early_stopping_patiences:
  validation_loss: 1000
early_stopping_upper_bounds:
  wall: 1.0e+100
ema_decay: 0.99
ema_use_num_updates: true
feature_irreps_hidden: 32x0e+32x1e+32x0o+32x1o
invariant_layers: 2
invariant_neurons: 64
l_max: 1
learning_rate: 0.005
log_batch_freq: 1
log_epoch_freq: 1
loss_coeffs:
  forces: 36846
  total_energy:
  - 1
  - PerAtomMSELoss
lr_scheduler_factor: 0.5
lr_scheduler_name: ReduceLROnPlateau
lr_scheduler_patience: 100
max_epochs: 200
max_gradient_norm: null
metrics_components:
- - forces
  - mae
- - forces
  - rmse
- - forces
  - mae
  - PerSpecies: true
    report_per_component: false
- - forces
  - rmse
  - PerSpecies: true
    report_per_component: false
- - total_energy
  - mae
- - total_energy
  - mae
  - PerAtom: true
metrics_key: validation_loss
n_train: 1000
n_val: 100
nonlinearity_gates:
  e: silu
  o: tanh
nonlinearity_scalars:
  e: silu
  o: tanh
nonlinearity_type: gate
num_basis: 8
num_features: 32
num_layers: 3
optimizer_amsgrad: true
optimizer_betas:
- 0.9
- 0.999
optimizer_eps: 1.0e-08
optimizer_name: Adam
optimizer_weight_decay: 0
parity: true
per_species_rescale_scales: dataset_forces_rms
per_species_rescale_scales_trainable: false
per_species_rescale_shifts: dataset_per_atom_total_energy_mean
per_species_rescale_shifts_trainable: false
r_max: 4.5
report_init_validation: false
resnet: false
root: results/toluene
run_name: ntrain_1000_lmax_1_invariant_1_epochs_200
save_checkpoint_freq: -1
save_ema_checkpoint_freq: -1
seed: 123
shuffle: true
train_val_split: random
use_ema: true
use_sc: true
verbose: info
