BesselBasis_trainable: true
PolynomialCutoff_p: 6
append: true
avg_num_neighbors: auto
batch_size: 5
chemical_embedding_irreps_out: 32x0e
chemical_symbols:
- H
- C
conv_to_output_hidden_irreps_out: 16x0e
dataset: npz
dataset_file_name: ./benchmark_data/toluene_ccsd_t-train.npz
dataset_seed: 456
dataset_url: http://quantum-machine.org/gdml/data/npz/toluene_ccsd_t.zip
default_dtype: float32
early_stopping_lower_bounds:
  LR: 1.0e-05
early_stopping_patiences:
  validation_loss: 50
ema_decay: 0.99
ema_use_num_updates: true
feature_irreps_hidden: 32x0e+32x1e+32x2e+32x3e+32x0o+32x1o+32x2o+32x3o
invariant_layers: 1
invariant_neurons: 64
irreps_edge_sh: 0e + 1o
key_mapping:
  E: total_energy
  F: forces
  R: pos
  z: atomic_numbers
l_max: 1
learning_rate: 0.005
log_batch_freq: 10
log_epoch_freq: 1
loss_coeffs:
  forces: 1
  total_energy:
  - 1
  - PerAtomMSELoss
lr_scheduler_factor: 0.5
lr_scheduler_name: ReduceLROnPlateau
lr_scheduler_patience: 100
max_epochs: 200
metrics_components:
- - forces
  - mae
- - forces
  - rmse
- - forces
  - mae
  - PerSpecies: true
    report_per_component: false
- - forces
  - rmse
  - PerSpecies: true
    report_per_component: false
- - total_energy
  - mae
- - total_energy
  - mae
  - PerAtom: true
metrics_key: validation_loss
n_train: 100
n_val: 50
nonlinearity_gates:
  e: silu
  o: tanh
nonlinearity_scalars:
  e: silu
  o: tanh
nonlinearity_type: gate
npz_fixed_field_keys:
- atomic_numbers
num_basis: 8
num_features: 32
num_layers: 1
optimizer_amsgrad: true
optimizer_name: Adam
per_species_rescale_scales: dataset_forces_rms
per_species_rescale_scales_trainable: false
per_species_rescale_shifts: dataset_per_atom_total_energy_mean
per_species_rescale_shifts_trainable: false
r_max: 4.0
report_init_validation: true
root: results/toluene
run_name: lmax_3_invariant_3_epochs_200
save_checkpoint_freq: -1
save_ema_checkpoint_freq: -1
seed: 123
shuffle: true
train_val_split: random
use_ema: true
use_sc: true
validation_batch_size: 10
verbose: info
wandb: true
wandb_project: toluene-example
