# general
root: results/aspirin
run_name: minimal_eng
seed: 0

# network
model_builder: nequip.models.EnergyModel
num_basis: 8
r_max: 4.0
irreps_edge_sh: 0e + 1o
conv_to_output_hidden_irreps_out: 16x0o + 16x0e + 16x1o + 16x1e + 16x2o + 16x2e
feature_irreps_hidden: 16x0o + 16x0e 

# data
dataset: aspirin
# A mapping of chemical species to type indexes is necessary if the dataset is provided with atomic numbers instead of type indexes.
chemical_symbol_to_type:
  H: 0
  C: 1
  O: 2
# Alternatively, if the dataset has type indexes, the total number of types is all that is required:
# type_names:
#   0: my_type
#   1: atom
#   2: thing

# logging
wandb: false
wandb_project: aspirin
# verbose: debug

# training
n_train: 5
n_val: 5
batch_size: 1
max_epochs: 10
learning_rate: 0.0

# loss function
loss_coeffs: 
  total_energy: 0.0001
  forces: 1.0

# optimizer
optimizer_name: Adam

PerSpeciesScaleShift_trainable: true
# # optional initial atomic energy shift for each species. in order of type. Defaults to zeros. 
# # Another option is to use "dataset_energy_mean", which automatically compute the per atom energy mean
# # but ^ this mode is not compatible with global_shift = "dataset_energy_mean"
PerSpeciesScaleShift_shifts: dataset_per_species_energy_mean
# # optional initial atomic energy scale for each species. in order of type. Defaults to ones.
# # Another option is to use "dataset_energy_std", which automatically compute the per atom energy mean
# # but ^ this mode is not compatible with global_shift = "dataset_energy_mean"
PerSpeciesScaleShift_scales: dataset_per_species_energy_std
PerSpeciesScaleShift_sigma: 4.0
global_rescale_shift: null
global_rescale_scale: dataset_force_rms
# global_rescale_scale: null
PerSpeciesScaleShift_enable: true