# general
root: results/aspirin
run_name: minimal
seed: 0

# network
num_basis: 8
r_max: 4.0
irreps_edge_sh: 0e + 1o
conv_to_output_hidden_irreps_out: 16x0e
feature_irreps_hidden: 16x0o + 16x0e + 16x1o + 16x1e + 16x2o + 16x2e

# data
dataset: aspirin
dataset_file_name: benchmark_data/aspirin_ccsd-train.npz
# A mapping of chemical species to type indexes is necessary if the dataset is provided with atomic numbers instead of type indexes.
chemical_symbol_to_type:
  H: 0
  C: 1
  O: 2
# Alternatively, if the dataset has type indexes, the total number of types is all that is required:
# species_names:
#   0: my_type
#   1: atom
#   2: thing

# logging
wandb: false
# verbose: debug

# training
n_train: 5
n_val: 5
batch_size: 1
max_epochs: 10

# loss function
loss_coeffs: forces

# optimizer
optimizer_name: Adam
