# general
root: results/w-14
run_name: minimal
seed: 123
dataset_seed: 456

# network
model_builders:
  - EnergyModel
  - PerSpeciesRescale
  - StressForceOutput
  - RescaleEnergyEtc
num_basis: 8
r_max: 4.0
irreps_edge_sh: 0e + 1o
conv_to_output_hidden_irreps_out: 16x0e
feature_irreps_hidden: 16x0o + 16x0e + 16x1o + 16x1e

# data set
dataset: ase                                                                       # type of data set, can be npz or ase
dataset_url: https://qmml.org/Datasets/w-14.zip             # url to download the npz. optional
dataset_file_name: ./benchmark_data/w-14.xyz                        # path to data set file
dataset_key_mapping:
  force: forces
  virial: stress
dataset_include_keys:
  - force
  - virial
# A mapping of chemical species to type indexes is necessary if the dataset is provided with atomic numbers instead of type indexes.
chemical_symbols:
  - W
# only early frames have stress
dataset_include_frames: !!python/object/apply:builtins.range
  - 0
  - 100
  - 1

global_rescale_scale: dataset_total_energy_std
per_species_rescale_shifts: dataset_per_atom_total_energy_mean
per_species_rescale_scales: dataset_per_atom_total_energy_std

# logging
wandb: false
# verbose: debug

# training
n_train: 90
n_val: 10
batch_size: 1
max_epochs: 10

# loss function
loss_coeffs:
 - stress
 - forces

# optimizer
optimizer_name: Adam
