# # python script/restart.py xxx/trainer.pth config/restart.yaml(optional)

# general
root: results/aspirin
wandb_project: aspirin
run_name: new_minimal
seed: 0
restart: true
append: false
verbose: debug
