root: results/water
run_name: water_lmax_1_100

seed: 123
dataset_seed: 456                                                                          
append: true                                                                     
default_dtype: float32                                                            
allow_tf32: false                                                                 
# device:  cuda                                                                     

# network
r_max: 4.5                                                                        
num_layers: 6                                                                    
dataset_url: https://github.com/BingqingCheng/ab-initio-thermodynamics-of-water/blob/master/training-set/dataset_1593.xyz
l_max: 1                                                                          
parity: true                                                                      
num_features: 32                                                                 

nonlinearity_type: gate                                                           
resnet: false                                                                     
                                                                                  
nonlinearity_scalars:
  e: silu
  o: tanh

nonlinearity_gates:
  e: silu
  o: tanh

# radial network basis
num_basis: 8                                                                     
BesselBasis_trainable: true                                                       
PolynomialCutoff_p: 6                                                             

# radial network
invariant_layers: 2                                                               
invariant_neurons: 64                                                             
avg_num_neighbors: auto                                                           
use_sc: true                                                                     


dataset: ase
dataset_file_name: /datasets/water/water-dataset.extxyz
ase_args:
  format: extxyz


chemical_symbol_to_type:
   H: 0
   O: 1


verbose: info                                                                      
log_batch_freq: 1                                                                  
log_epoch_freq: 1                                                                  
save_checkpoint_freq: -1                                                           
save_ema_checkpoint_freq: -1                                                       

# training
n_train: 100                                                                      
n_val: 100                                                                         
learning_rate: 0.005                                                               
batch_size: 1                                                                      
max_epochs: 1000000                                                                     
train_val_split: random                                                            
shuffle: true                                                                      
metrics_key: validation_loss                                                        
use_ema: true                                                                      
ema_decay: 0.99                                                                    
ema_use_num_updates: true                                                          
report_init_validation: false                                                      


early_stopping_patiences:                                                          
  validation_loss: 1000

early_stopping_delta:                                                              
  validation_loss: 0.005

early_stopping_cumulative_delta: false                                            

early_stopping_lower_bounds:                                                       
  LR: 1.0e-6

early_stopping_upper_bounds:                                                       
  wall: 1.0e+100
                                                          
# loss function
loss_coeffs:                                                                       
  forces: 36846                                                                       
  total_energy:                                                                    
    - 1
    - PerAtomMSELoss



# output metrics
metrics_components:
  - - forces                               # key 
    - mae                                  # "rmse" or "mae"
  - - forces
    - rmse
  - - forces
    - mae
    - PerSpecies: True                     # if true, per species contribution is counted separately
      report_per_component: False          # if true, statistics on each component (i.e. fx, fy, fz) will be counted separately
  - - forces                                
    - rmse                                  
    - PerSpecies: True                     
      report_per_component: False    
  - - total_energy
    - mae    
  - - total_energy
    - mae
    - PerAtom: True                        # if true, energy is normalized by the number of atoms                 

optimizer_name: Adam                                                               
optimizer_amsgrad: true
optimizer_betas: 
  - 0.9
  - 0.999
optimizer_eps: 1.0e-08
optimizer_weight_decay: 0

max_gradient_norm: null


lr_scheduler_name: ReduceLROnPlateau
lr_scheduler_patience: 100
lr_scheduler_factor: 0.5


per_species_rescale_scales_trainable: false

per_species_rescale_shifts_trainable: false

per_species_rescale_shifts: dataset_per_atom_total_energy_mean
per_species_rescale_scales: dataset_forces_rms
